spring:
  datasource:
    url: jdbc:h2:file:~/springDemo
    username: sa
    password:
    driverClassName: org.h2.Driver

  h2:
    console:
      enabled: true
      path: /h2
      settings:
        web-allow-others: true
  main:
    allow-bean-definition-overriding: true

  jpa:
    #    properties.javax.persistence.schema-generation.create-source: metadata
    #    properties.javax.persistence.schema-generation.scripts.action: create
    #    properties.javax.persistence.schema-generation.scripts.create-target: create.sql

    hibernate:
      ddl-auto: create-drop


logging:
  level:
    org:
      hibernate:
        sql: info
#        type:
#          descriptor:
#            sql:trace